using System;
using System.IO.IsolatedStorage;

namespace jsimple.io
{
    public class WindowsDesktopPaths : Paths
    {
        private static readonly object lockObject = new Object();
        static volatile FileSystemDirectory applicationDataDirectory = null;

        /// <returns> the directory where the application should store its private data. </returns>
        public override Directory ApplicationDataDirectory
        {
            get
            {
                if (applicationDataDirectory == null)
                {
                    lock (lockObject)
                    {
                        if (applicationDataDirectory == null)
                            applicationDataDirectory = new FileSystemDirectory("c:\\foo");
                    }
                }
                return applicationDataDirectory;
            }
        }

        /// <summary>
        /// Get the test output directory for the specified test name.  This directory is normally under
        /// <projectBase>/target/test-output/<testName>.  Any existing directory will have its contents deleted by this
        /// method, before returning.  The idea here is that test output sticks around after the tests are run, so it can be
        /// inspected to maybe do some debugging.  But it's under "target" so it shouldn't show up as new files for source
        /// control, just intermediate output generated by the build.
        /// </summary>
        /// <param name="testName"> test name, used as part of directory name </param>
        /// <returns> directory to hold test output </returns>
        public override Directory getTestOutputDirectory(string testName)
        {
            Directory projectDirectory = ApplicationDataDirectory;
            Directory testOutputBase = projectDirectory.createDirectory("target").createDirectory("test-output");

            return testOutputBase.createDirectory(testName);
        }

        /// <summary>
        /// Return the Directory object corresponding to the string serialized representation.  If the directory doesn't
        /// exist, it's implementation dependent whether this method throws a PathNotFoundException or a
        /// PathNotFoundException is thrown when the returned directory is used--different implementations do different
        /// things there.
        /// <p/>
        /// Not all implementations of Directory support serializing it as a string.  An exception is thrown if it's not
        /// supported.
        /// </summary>
        /// <param name="directoryPathString">
        /// @return </param>
        public override Directory getDirectory(string directoryPathString)
        {
            return new FileSystemDirectory(directoryPathString);
        }
    }
}